"""add walk forward fields to backtest results

Revision ID: 4854af26a1fe
Revises: 7407fc1421a9
Create Date: 2026-02-17 16:36:42.764774+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4854af26a1fe'
down_revision: Union[str, None] = '7407fc1421a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_results', sa.Column('is_walk_forward', sa.Boolean(), nullable=True))
    op.add_column('backtest_results', sa.Column('is_overfitted', sa.Boolean(), nullable=True))
    op.add_column('backtest_results', sa.Column('walk_forward_efficiency', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('backtest_results', sa.Column('spread_model', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_results', 'spread_model')
    op.drop_column('backtest_results', 'walk_forward_efficiency')
    op.drop_column('backtest_results', 'is_overfitted')
    op.drop_column('backtest_results', 'is_walk_forward')
    # ### end Alembic commands ###
